#!/usr/bin/env python
# encoding: utf-8

name = "seed"
shortDesc = ""
longDesc = """

"""
autoGenerated=True
entry(
    index = 0,
    label = "H + H <=> H2",
    degeneracy = 0.5,
    kinetics = Arrhenius(A=(5.45e+10,'cm^3/(mol*s)'), n=0, Ea=(6.276,'kJ/mol'), T0=(1,'K'), Tmin=(278,'K'), Tmax=(372,'K'), comment="""Matched reaction 56 H + H <=> H2 in R_Recombination/training
    This reaction matched rate rule [Root_1R->H_N-2R->S_2CHNO->H]
    family: R_Recombination"""),
    longDesc = 
"""
Matched reaction 56 H + H <=> H2 in R_Recombination/training
This reaction matched rate rule [Root_1R->H_N-2R->S_2CHNO->H]
family: R_Recombination
""",
)

entry(
    index = 1,
    label = "O2 + H2 <=> H + [O]O",
    degeneracy = 4.0,
    kinetics = Arrhenius(A=(2.9e+14,'cm^3/(mol*s)','*|/',5), n=0, Ea=(236.982,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(800,'K'), comment="""Matched reaction 305 H2 + O2 <=> HO2_r12 + H in H_Abstraction/training
    This reaction matched rate rule [H2;O2b]
    family: H_Abstraction"""),
    longDesc = 
"""
Matched reaction 305 H2 + O2 <=> HO2_r12 + H in H_Abstraction/training
This reaction matched rate rule [H2;O2b]
family: H_Abstraction
""",
)

entry(
    index = 2,
    label = "O2 + H <=> [O]O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(8.79e+10,'cm^3/(mol*s)'), n=1, Ea=(1.8828,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(6000,'K'), comment="""Matched reaction 104 O2 + H <=> HO2-2 in R_Recombination/training
    This reaction matched rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_N-Sp-3R!H=2CCNNOO_2CNO->O_3R!H->O]
    family: R_Recombination"""),
    longDesc = 
"""
Matched reaction 104 O2 + H <=> HO2-2 in R_Recombination/training
This reaction matched rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_N-Sp-3R!H=2CCNNOO_2CNO->O_3R!H->O]
family: R_Recombination
""",
)

entry(
    index = 3,
    label = "H + OO <=> [O]O + H2",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(1.1185,'m^3/(mol*s)'), n=1.66084, Ea=(28.0205,'kJ/mol'), T0=(1,'K'), comment="""Estimated using average of templates [O/H/NonDeO;H_rad] + [H2O2;Y_rad] for rate rule [H2O2;H_rad]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using average of templates [O/H/NonDeO;H_rad] + [H2O2;Y_rad] for rate rule [H2O2;H_rad]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: H_Abstraction
""",
)

entry(
    index = 4,
    label = "H + [O]O <=> OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5250.69,'m^3/(mol*s)'), n=1.27262, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.1368631905, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_N-Sp-3R!H=2CCNNOO_2CNO->O_3R!H->O',), comment="""Estimated from node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_N-Sp-3R!H=2CCNNOO_2CNO->O_3R!H->O in family R_Recombination."""),
    longDesc = 
"""
Estimated from node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_N-Sp-3R!H=2CCNNOO_2CNO->O_3R!H->O in family R_Recombination.
""",
)

entry(
    index = 5,
    label = "[O]O + [O]O <=> O2 + OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.75e+10,'cm^3/(mol*s)'), n=0, Ea=(-13.7026,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 404 HO2_r3 + HO2_r12 <=> H2O2 + O2 in H_Abstraction/training
    This reaction matched rate rule [Orad_O_H;O_rad/NonDeO]
    family: H_Abstraction"""),
    longDesc = 
"""
Matched reaction 404 HO2_r3 + HO2_r12 <=> H2O2 + O2 in H_Abstraction/training
This reaction matched rate rule [Orad_O_H;O_rad/NonDeO]
family: H_Abstraction
""",
)

entry(
    index = 6,
    label = "OH(D) + OH(D) <=> OO",
    degeneracy = 0.5,
    kinetics = Arrhenius(A=(7.85e+12,'cm^3/(mol*s)','+|-',6.02e+12), n=(0,'','+|-',0.5), Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(400,'K'), comment="""Matched reaction 96 OH + OH <=> H2O2 in R_Recombination/training
    This reaction matched rate rule [Root_N-1R->H_N-1CNOS->N_1COS->O_N-2R->C]
    family: R_Recombination"""),
    longDesc = 
"""
Matched reaction 96 OH + OH <=> H2O2 in R_Recombination/training
This reaction matched rate rule [Root_N-1R->H_N-1CNOS->N_1COS->O_N-2R->C]
family: R_Recombination
""",
)

entry(
    index = 7,
    label = "OH(D) + H2 <=> H + H2O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(1.82e+09,'cm^3/(mol*s)'), n=1.21, Ea=(83.9729,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(2400,'K'), comment="""Matched reaction 311 H2 + OH <=> H2O_p + H_p in H_Abstraction/training
    This reaction matched rate rule [H2;O_pri_rad]
    family: H_Abstraction"""),
    longDesc = 
"""
Matched reaction 311 H2 + OH <=> H2O_p + H_p in H_Abstraction/training
This reaction matched rate rule [H2;O_pri_rad]
family: H_Abstraction
""",
)

entry(
    index = 8,
    label = "H + OH(D) <=> H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.62e+14,'cm^3/(mol*s)'), n=0, Ea=(0.6276,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2100,'K'), comment="""Matched reaction 64 H + OH <=> H2O in R_Recombination/training
    This reaction matched rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_2CNO->O]
    family: R_Recombination"""),
    longDesc = 
"""
Matched reaction 64 H + OH <=> H2O in R_Recombination/training
This reaction matched rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_2CNO->O]
family: R_Recombination
""",
)

entry(
    index = 9,
    label = "O2 + H2O <=> OH(D) + [O]O",
    degeneracy = 4.0,
    kinetics = Arrhenius(A=(9.3e+12,'cm^3/(mol*s)'), n=0, Ea=(310.118,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1000,'K'), comment="""Matched reaction 378 H2O + O2 <=> HO2_r12 + OH_p23 in H_Abstraction/training
    This reaction matched rate rule [Orad_O_H;O_pri_rad]
    family: H_Abstraction"""),
    longDesc = 
"""
Matched reaction 378 H2O + O2 <=> HO2_r12 + OH_p23 in H_Abstraction/training
This reaction matched rate rule [Orad_O_H;O_pri_rad]
family: H_Abstraction
""",
)

entry(
    index = 10,
    label = "OH(D) + OO <=> [O]O + H2O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(0.4995,'m^3/(mol*s)'), n=1.9275, Ea=(26.4644,'kJ/mol'), T0=(1,'K'), comment="""Estimated using average of templates [O/H/NonDeO;O_pri_rad] + [H2O2;O_rad] for rate rule [H2O2;O_pri_rad]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using average of templates [O/H/NonDeO;O_pri_rad] + [H2O2;O_rad] for rate rule [H2O2;O_pri_rad]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: H_Abstraction
""",
)

entry(
    index = 11,
    label = "O2 + OH(D) <=> O2(S) + OH(D)",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(4e+07,'m^3/(mol*s)'), n=1.78837e-07, Ea=(94.3116,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.1368631905, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_N-2R->C_N-3R!H->N_2OS->O',), comment="""Estimated from node Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_N-2R->C_N-3R!H->N_2OS->O in family R_Recombination.
    Multiplied by reaction path degeneracy 2.0
    Ea raised from 94.3 to 94.3 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated from node Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_N-2R->C_N-3R!H->N_2OS->O in family R_Recombination.
Multiplied by reaction path degeneracy 2.0
Ea raised from 94.3 to 94.3 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 12,
    label = "O(T) + OH(D) <=> [O]O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(15.4803,'m^3/(mol*s)'), n=1.88017, Ea=(5.1666,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [O_rad;O_birad] for rate rule [O_pri_rad;O_birad]
    Euclidian distance = 1.0
    family: Birad_R_Recombination"""),
    longDesc = 
"""
Estimated using template [O_rad;O_birad] for rate rule [O_pri_rad;O_birad]
Euclidian distance = 1.0
family: Birad_R_Recombination
""",
)

entry(
    index = 13,
    label = "O(T) + H <=> OH(D)",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 4 H + O <=> HO in Birad_R_Recombination/training
    This reaction matched rate rule [H_rad;O_birad]
    family: Birad_R_Recombination"""),
    longDesc = 
"""
Matched reaction 4 H + O <=> HO in Birad_R_Recombination/training
This reaction matched rate rule [H_rad;O_birad]
family: Birad_R_Recombination
""",
)

entry(
    index = 14,
    label = "O(T) + [O]O <=> O2 + OH(D)",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3820.63,'m^3/(mol*s)'), n=0.685179, Ea=(22.1161,'kJ/mol'), T0=(1,'K'), comment="""Estimated using average of templates [X_H;O_atom_triplet] + [Orad_O_H;Y_rad_birad_trirad_quadrad] for rate rule [Orad_O_H;O_atom_triplet]
    Euclidian distance = 2.0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using average of templates [X_H;O_atom_triplet] + [Orad_O_H;Y_rad_birad_trirad_quadrad] for rate rule [Orad_O_H;O_atom_triplet]
Euclidian distance = 2.0
family: H_Abstraction
""",
)

entry(
    index = 15,
    label = "O(T) + H2 <=> H + OH(D)",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(3.4e+08,'cm^3/(mol*s)'), n=1.5, Ea=(96.0228,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 285 H2 + O_rad <=> HO + H in H_Abstraction/training
    This reaction matched rate rule [OH_rad_H;H_rad]
    family: H_Abstraction"""),
    longDesc = 
"""
Matched reaction 285 H2 + O_rad <=> HO + H in H_Abstraction/training
This reaction matched rate rule [OH_rad_H;H_rad]
family: H_Abstraction
""",
)

entry(
    index = 16,
    label = "O(T) + OO <=> OH(D) + [O]O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(1.74e+13,'cm^3/(mol*s)'), n=0, Ea=(19.874,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [O/H/NonDeO;O_atom_triplet] for rate rule [H2O2;O_atom_triplet]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using template [O/H/NonDeO;O_atom_triplet] for rate rule [H2O2;O_atom_triplet]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: H_Abstraction
""",
)

entry(
    index = 17,
    label = "O(T) + H2O <=> OH(D) + OH(D)",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(5.26e+09,'cm^3/(mol*s)'), n=1.2, Ea=(74.6007,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(1000,'K'), comment="""Matched reaction 379 H2O + O_rad <=> HO + OH_p23 in H_Abstraction/training
    This reaction matched rate rule [OH_rad_H;O_pri_rad]
    family: H_Abstraction"""),
    longDesc = 
"""
Matched reaction 379 H2O + O_rad <=> HO + OH_p23 in H_Abstraction/training
This reaction matched rate rule [OH_rad_H;O_pri_rad]
family: H_Abstraction
""",
)

entry(
    index = 18,
    label = "O(T) + [O]O <=> O2(S) + OH(D)",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(15.4803,'m^3/(mol*s)'), n=1.88017, Ea=(5.1666,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""From training reaction 3 used for O_rad/NonDe;O_birad
    Exact match found for rate rule [O_rad/NonDe;O_birad]
    Euclidian distance = 0
    family: Birad_R_Recombination"""),
    longDesc = 
"""
From training reaction 3 used for O_rad/NonDe;O_birad
Exact match found for rate rule [O_rad/NonDe;O_birad]
Euclidian distance = 0
family: Birad_R_Recombination
""",
)

