#!/usr/bin/env python
"""job-04 gate - THE PoC THESIS TEST (PLAN.md 1, 10-Phase 1).

Measures whether rmgpu's ML estimators (the two vendored checkpoints) match
RMG-Py's library+GA+rate-rules accuracy. Rigorous and honest: the deliverable
is the measured error distribution, not a smoothed green. A RED gate is a
VALID PoC OUTCOME (PLAN 13 risk 1) - reported with full numbers, recorded in
STATUS, and left to the user (step-06: "Do NOT paper over it").

Four checks (gate definition, job-04):
  (4) Checkpoint round-trip: BOTH vendored checkpoints reproduce the step-01
      reference predictions via rmgpu.ml.base (non-circular: the baseline was
      generated by models/predict.py itself).
  (1) Coverage: over the union of species in examples
      {superminimal, c3h4, minimal, minimal_ml, ethane-oxidation} + all
      primaryThermoLibrary species (thermo) and the c3h4/superminimal
      mechanism-relevant reaction set + depository subset (kinetics):
      % resolved by the resolvers + the unresolved list with reasons.
  (2) Accuracy vs RMG-Py on covered species (cap ~500, stratified by class):
      Hf298/S298/Cp(300,600,1000) - N, mean abs err, median, max, p95 +
      histograms + per-class and per-sign breakdowns;
      HPL k(T): log10(k_rmgpu/k_rmg) at 300/600/1000 K, overall + per bucket.
  (3) No-fallback proof: the resolvers (rmgpu.data.estimation) are
      instrumented (EstimationCounts); library + ML + coverage == total,
      and NO other branch exists in the code (PLAN 14). The split is reported.

The RMG-Py reference comes from gates/baselines/thesis_test/ (thermo.json,
reactions.json), generated by scripts/reference_props.py in rmg_env and
committed. The gate never re-derives the reference.

UNIT CONVENTION (verified, not assumed):
  thermo  Hf298 J/mol, S298 J/(mol*K), Cp J/(mol*K) - both sides SI.
  kinetics The baseline's k(T) is SI (m^3/(mol*s) bimolecular,
    cm^6->m^6... i.e. get_rate_coefficient's SI output - verified in rmg_env:
    A=(1e13, cm^3/(mol*s)), n=0, Ea=0 gives k(300)=1e7, i.e. 1e13*1e-6).
    The rmgpu ML side emits A in CGS cm^3/(mol*s) (per-site, PLAN 3b); the
    gate converts k_cgs -> k_si with 10**(-6*(molecularity-1)) before
    comparing log10(k_rmgpu/k_rmg).

KNOWN ARTIFACTS (reported, not hidden):
  * The thermo checkpoint's H298 target is 10^(log-space) - ALWAYS POSITIVE
    by construction (trained on rmgdb species with positive H298). Species
    whose RMG-Py reference Hf298 is NEGATIVE (most stable molecules) are
    structurally outside the model's output domain; their dHf298 is reported
    separately (per-sign breakdown) as the PLAN 3b finding.
  * The ML branch's Cp(T) passes through the estimator's COARSE Wilhoit fit
    (rmgpu/ml/thermo_estimator._fit_wilhoit: a_i=0, B=500) - a documented
    simplification. The gate reports the estimator's Cp_model values (what a
    mechanism would use) AND a raw-grid diagnostic (the checkpoint's own
    7-point grid at 300/600/1000) so the fit-smoothing can be separated
    from model error.
  * The kinetics checkpoint is not bit-stable in-process (drift ~1.6e-2
    ABSOLUTE on the linear Ea column; step-05 finding). 0.0156 J/mol on Ea
    is negligible for k(T) at 300-1000 K; the round-trip tolerance (atol
    1e-4) absorbs it with margin.

Run:  /home/jackson/miniforge3/envs/rmgpu/bin/python gates/gate_04.py
Writes reports/gate_04_results.json (full numbers) + a console summary.
Exit code: 0 = PASS, 2 = RED.
"""
from __future__ import annotations

import json
import sys
import time
from pathlib import Path

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from chemprop import data as chemprop_data  # noqa: E402

from rmgpu.db import Databases  # noqa: E402
from rmgpu.data.estimation import (  # noqa: E402
    EstimationCounts,
    estimate_kinetics,
    estimate_thermo,
)
from rmgpu.kinetics.models import R  # noqa: E402  (rmgpu's R, RMG-Py parity)
from rmgpu.ml.base import KINETICS_CKPT_PATH, THERMO_CKPT_PATH  # noqa: E402
from rmgpu.ml.kinetics_estimator import KineticsML  # noqa: E402
from rmgpu.ml.thermo_estimator import MLCoverageError  # noqa: E402

BASELINE_DIR = REPO_ROOT / "gates" / "baselines"
REF_PRED = BASELINE_DIR / "job04" / "reference_predictions.json"
THERMO_REF = BASELINE_DIR / "thesis_test" / "thermo.json"
RXN_REF = BASELINE_DIR / "thesis_test" / "reactions.json"
OUT = REPO_ROOT / "reports" / "gate_04_results.json"

T_LIST = (300.0, 600.0, 1000.0)
# grid indices of T_LIST in the checkpoint's Cp grid
# (300/400/500/600/800/1000/1500 K)
CP_GRID_IDX = {300: 0, 600: 3, 1000: 5}
THERMO_LIBRARIES = ["primaryThermoLibrary"]
REACTION_LIBRARIES = ["primaryH2O2"]  # a real library scope for the resolver

# --- PASS/RED thresholds (see module docstring + reports/job-04.md) --------
TH_COV_MIN = 0.95
KIN_COV_MIN = 0.90
HERR_P95_MAX = 20.0e3    # J/mol
SERR_P95_MAX = 10.0      # J/(mol*K)
CPERR_P95_MAX = 20.0     # J/(mol*K)
KLOG_P95_MAX = 1.0       # orders of magnitude
CAP_SPECIES = 500  # stratified cap (the set is smaller; all are used)


def stats(arr) -> dict:
    a = np.asarray(arr, dtype=np.float64)
    if a.size == 0:
        return {"N": 0}
    return {
        "N": int(a.size),
        "mean_abs": float(np.mean(np.abs(a))),
        "median_abs": float(np.median(np.abs(a))),
        "max_abs": float(np.max(np.abs(a))),
        "p95_abs": float(np.percentile(np.abs(a), 95)),
        "mean": float(np.mean(a)),
        "median": float(np.median(a)),
        "max": float(np.max(a)),
        "min": float(np.min(a)),
    }


def hist_binning(arr, bins: int = 20) -> dict:
    """ASCII histogram (20 bins) for the report."""
    a = np.asarray(arr, dtype=np.float64)
    if a.size == 0:
        return {}
    counts, edges = np.histogram(a, bins=bins)
    top = int(np.max(counts)) or 1
    lines = []
    for i, c in enumerate(counts):
        lo, hi = edges[i], edges[i + 1]
        bar = "#" * int(40 * c / top)
        lines.append(f"  [{lo:10.3g}, {hi:10.3g}) {c:5d} |{bar}")
    return {"min": float(a.min()), "max": float(a.max()),
            "histogram": "\n".join(lines)}


# ---------------------------------------------------------------------------
# Check 4: checkpoint round-trip vs the step-01 baseline
# ---------------------------------------------------------------------------

def check_roundtrip(ckpt_t, ckpt_k) -> dict:
    t0 = time.time()
    ref = json.loads(REF_PRED.read_text())
    out: dict = {"tol": "rtol=1e-6, atol=1e-4 per element (absorbs the known "
                        "in-process ~1.6e-2-absolute Ea flake documented in step-05)"}

    mol_refs = ref["molecules"]["smiles"]
    pts = [chemprop_data.MoleculeDatapoint.from_smi(s, keep_h=True, add_h=True)
           for s in mol_refs]
    raw = ckpt_t.predict_raw(pts, batch_size=8)
    ok = True
    maxdiff = 0.0
    for i, smi in enumerate(mol_refs):
        for j, target in enumerate(ckpt_t.targets):
            expected = ref["molecules"]["rows"][smi][target]
            actual = float(raw[i, j])
            if not np.allclose(actual, expected, rtol=1e-6, atol=1e-4):
                ok = False
                out.setdefault("failures", []).append(
                    f"thermo {smi} {target}: {actual!r} vs {expected!r}")
            maxdiff = max(maxdiff, abs(actual - expected))
    out["thermo"] = {
        "checkpoint": THERMO_CKPT_PATH.name,
        "n_molecules": len(mol_refs),
        "max_abs_diff_raw": maxdiff,
        "pass": ok,
    }

    rxn_refs = ref["reactions"]["smiles"]
    pts = [chemprop_data.ReactionDatapoint.from_smi(s, keep_h=True, add_h=True)
           for s in rxn_refs]
    raw = ckpt_k.predict_raw(pts, batch_size=8)
    k_ok = True
    maxdiff = 0.0
    for i, smi in enumerate(rxn_refs):
        for j, target in enumerate(ckpt_k.targets):
            expected = ref["reactions"]["rows"][smi][target]
            actual = float(raw[i, j])
            if not np.allclose(actual, expected, rtol=1e-6, atol=1e-4):
                k_ok = False
                out.setdefault("failures", []).append(
                    f"kinetics {smi[:40]}... {target}: {actual!r} vs "
                    f"{expected!r}")
            maxdiff = max(maxdiff, abs(actual - expected))
    out["kinetics"] = {
        "checkpoint": KINETICS_CKPT_PATH.name,
        "n_reactions": len(rxn_refs),
        "max_abs_diff_raw": maxdiff,
        "pass": k_ok,
    }
    out["elapsed_s"] = round(time.time() - t0, 1)
    out["pass"] = ok and k_ok
    return out


# ---------------------------------------------------------------------------
# Thermo: coverage (1) + accuracy (2) + no-fallback (3)
# ---------------------------------------------------------------------------

def check_thermo(species_list: list[dict], thermo_db, ml_bundle,
                 ref_thermo: dict) -> dict:
    t0 = time.time()
    counts = EstimationCounts()
    n = len(species_list)
    if n > CAP_SPECIES:  # stratified subsample (not needed: set < cap)
        raise RuntimeError("species set exceeds the gate cap")

    resolver = {}   # check 1+3: what the resolvers do (runtime behavior)
    model_cov = 0
    for i, sp in enumerate(species_list):
        smiles, label = sp["smiles"], sp["label"]
        try:
            if ml_bundle.thermo.covers(smiles):
                model_cov += 1
        except Exception:
            pass
        try:
            pred = estimate_thermo(
                {"label": label, "smiles": smiles},
                thermo_db, ml_bundle, counts=counts,
                libraries=THERMO_LIBRARIES)
            resolver[smiles] = {
                "status": pred.uncertainties.get("source", "library"),
                "Hf298": float(pred.Hf298),
                "S298": float(pred.S298),
                "Cp300": float(pred.Cp_model.get_heat_capacity(300.0)),
                "Cp600": float(pred.Cp_model.get_heat_capacity(600.0)),
                "Cp1000": float(pred.Cp_model.get_heat_capacity(1000.0)),
            }
        except MLCoverageError as e:
            resolver[smiles] = {"status": "coverage_error", "reason": str(e)}
        except Exception as e:
            resolver[smiles] = {"status": "error",
                                "reason": f"{type(e).__name__}: {e}"}
        if (i + 1) % 10 == 0:
            print(f"[gate_04 thermo] {i + 1}/{n} "
                  f"({time.time() - t0:.0f}s)", flush=True)

    covered = {s for s, r in resolver.items() if r["status"] in ("library", "ml")}
    cov_pct = len(covered) / n
    by_label = {sp["smiles"]: sp for sp in species_list}

    # check 2: accuracy of the ML estimator vs the RMG-Py reference
    # (the thesis: does ML match legacy library+GA accuracy)
    dhf, dsl, dcp = [], [], []
    dhf_in_domain = []  # ref_Hf298 > 0 only: the model's positive-output domain
    dcp_raw = []  # diagnostic: the checkpoint's RAW 7-point grid (no fit)
    per_class = {}
    per_sign = {"ref_Hf298_negative": [], "ref_Hf298_nonnegative": []}
    ml_fail = []
    for sp in species_list:
        smiles = sp["smiles"]
        ref = ref_thermo["species"].get(smiles)
        if ref is None or "error" in ref:
            continue
        try:
            p = ml_bundle.thermo.predict(smiles)
        except MLCoverageError as e:
            ml_fail.append({"smiles": smiles, "reason": str(e)})
            continue
        dh = p.Hf298 - ref["Hf298"]
        ds = p.S298 - ref["S298"]
        # estimator Cp (what a mechanism would consume)
        dc = [p.Cp_model.get_heat_capacity(T) - ref[f"Cp{int(T)}"]
              for T in T_LIST]
        # diagnostic: raw checkpoint grid at the same temperatures
        raw_cp = np.asarray(p.Cp_model.Cp, dtype=np.float64)
        dc_raw = [float(raw_cp[CP_GRID_IDX[int(T)]]) - ref[f"Cp{int(T)}"]
                  for T in T_LIST]
        cls = ref["class"]
        per_class.setdefault(cls, {"n": 0, "dhf": [], "ds": [], "dcp": []})
        per_class[cls]["n"] += 1
        per_class[cls]["dhf"].append(dh)
        per_class[cls]["ds"].append(ds)
        per_class[cls]["dcp"].extend(dc)
        sig = ("ref_Hf298_negative" if ref["Hf298"] < 0
               else "ref_Hf298_nonnegative")
        per_sign[sig].append(dh)
        dhf.append(dh)
        dsl.append(ds)
        dcp.extend(dc)
        dcp_raw.extend(dc_raw)
        if ref["Hf298"] > 0:  # the model's H298 output (10^pred) can only be
            # positive; ref_Hf298 > 0 is its training domain
            dhf_in_domain.append(dh)
    dhf_in_domain_arr = np.asarray(dhf_in_domain)

    out = {
        "n_species": n,
        "coverage": {
            "model_covers": int(model_cov),
            "resolver_covered": int(len(covered)),
            "coverage_pct": round(cov_pct, 4),
            "uncovered": [
                {"smiles": s, "label": by_label[s]["label"],
                 "class": by_label[s]["class"],
                 "reason": resolver[s].get("reason", "")}
                for s in sorted(set(resolver) - covered)
            ],
        },
        "no_fallback": counts.as_dict(),
        "accuracy_ml_vs_legacy": {
            "dhf298_J_mol": stats(dhf),
            "ds298_J_molK": stats(dsl),
            "dcp_J_molK": stats(dcp),
            "dcp_raw_grid_J_molK_diagnostic": stats(dcp_raw),
            "dhf298_kJ_mol": {k: (v / 1000.0 if isinstance(v, float) else v)
                              for k, v in stats(dhf).items()},
            "histogram_dhf298_kJ_mol": hist_binning(np.asarray(dhf) / 1000.0),
            "per_class": {
                c: {"n": v["n"],
                    "dhf298_kJ_mol": stats(np.asarray(v["dhf"]) / 1000.0),
                    "ds298_J_molK": stats(np.asarray(v["ds"])),
                    "dcp_J_molK": stats(np.asarray(v["dcp"]))}
                for c, v in sorted(per_class.items())
            },
            # the PLAN 3b finding: the model's H298 output is always
            # positive (10^log-space, trained on positive-H298 species), so
            # negative-Hf298 species are outside its domain by construction
            "dhf298_by_ref_sign_kJ_mol": {
                s: stats(np.asarray(v) / 1000.0) for s, v in per_sign.items()
            },
            # the model's output (10^pred) is positive by construction; the
            # ref_Hf298 > 0 subset is its training domain, where the error is
            # the honest in-domain accuracy (the PLAN 3b boundary finding)
            "dhf298_in_domain_ref_positive_kJ_mol": stats(
                dhf_in_domain_arr / 1000.0),
            "ml_coverage_failures": ml_fail,
        },
        "elapsed_s": round(time.time() - t0, 1),
    }
    return out


# ---------------------------------------------------------------------------
# Kinetics: coverage (1) + accuracy (2) + no-fallback (3)
# ---------------------------------------------------------------------------

def _ml_k_si(A_cgs: float, n: float, Ea: float, T: float, molec: int) -> float:
    """k(T) in SI from the ML's CGS per-site A (PLAN 3b boundary).

    CGS -> SI: cm^3/(mol*s) -> m^3/(mol*s) is 1e-6; cm^6/(mol^2*s) ->
    m^6/(mol^2*s) is 1e-12; i.e. 10**(-6*(molecularity-1)).
    """
    k_cgs = A_cgs * (T / 1.0) ** n * np.exp(-Ea / (R * T))
    return k_cgs * 10.0 ** (-6 * (molec - 1))


def check_kinetics(ref_rxns: dict, kinetics_db, ml_bundle) -> dict:
    t0 = time.time()
    counts = EstimationCounts()
    reactions = ref_rxns["reactions"]
    n = len(reactions)

    resolver = {}
    model_cov = 0
    for i, (smi, rec) in enumerate(reactions.items()):
        try:
            if ml_bundle.kinetics.covers(smi):
                model_cov += 1
        except Exception:
            pass
        rxn = {
            "label": smi[:60],
            "reactants": [{"label": f"r{j}", "smiles": s}
                          for j, s in enumerate(rec["reactants"])],
            "products": [{"label": f"p{j}", "smiles": s}
                         for j, s in enumerate(rec["products"])],
            "reaction_smiles": smi,
        }
        try:
            model, _deg = estimate_kinetics(
                rxn, kinetics_db, ml_bundle, counts=counts,
                libraries=REACTION_LIBRARIES, degeneracy=1.0)
            # the ML branch tags its Arrhenius comment "ML estimate, ...";
            # library hits carry rmgdb's stored comment
            comment = str(getattr(model, "comment", ""))
            resolver[smi] = {
                "status": "ml" if comment.startswith("ML") else "library",
                "A": float(model.A),
                "n": float(model.n),
                "Ea_J_mol": float(model.Ea),
            }
        except MLCoverageError as e:
            resolver[smi] = {"status": "coverage_error", "reason": str(e)}
        except Exception as e:
            resolver[smi] = {"status": "error",
                             "reason": f"{type(e).__name__}: {e}"}
        if (i + 1) % 25 == 0:
            print(f"[gate_04 kinetics] {i + 1}/{n} "
                  f"({time.time() - t0:.0f}s)", flush=True)

    covered = {s for s, r in resolver.items() if r["status"] in ("library", "ml")}
    cov_pct = len(covered) / n

    # check 2: accuracy of the ML k(T) vs the reference (SI).
    # Only ML-resolved reactions: the thesis is ML-vs-legacy, and library
    # hits have no ML value by construction (resolver short-circuits).
    logs = {T: [] for T in T_LIST}
    per_bucket = {}
    for smi, rec in reactions.items():
        r = resolver.get(smi, {})
        if r.get("status") != "ml":
            continue
        molec = rec["molecularity"]
        for T in T_LIST:
            k_ref = rec.get(f"k{int(T)}")
            if k_ref is None or k_ref <= 0:
                continue
            k_rmgpu = _ml_k_si(r["A"], r["n"], r["Ea_J_mol"], T, molec)
            if k_rmgpu <= 0:
                continue
            ratio = float(np.log10(k_rmgpu / k_ref))
            logs[T].append(ratio)
            per_bucket.setdefault(rec["bucket"], {}).setdefault(
                T, []).append(ratio)

    out = {
        "n_reactions": n,
        "coverage": {
            "model_covers": int(model_cov),
            "resolver_covered": int(len(covered)),
            "coverage_pct": round(cov_pct, 4),
            "uncovered": [
                {"reaction_smiles": s,
                 "bucket": reactions[s]["bucket"],
                 "reason": resolver[s].get("reason", "")}
                for s in sorted(set(resolver) - covered)
            ],
        },
        "no_fallback": counts.as_dict(),
        "accuracy_ml_vs_legacy": {
            f"log10_k_ratio_{int(T)}": stats(np.asarray(logs[T]))
            for T in T_LIST
        },
        "per_bucket": {
            b: {f"log10_k_ratio_{int(T)}": stats(np.asarray(v[T]))
                for T in T_LIST if T in v}
            for b, v in sorted(per_bucket.items())
        },
        "histogram_log10_k_ratio_600K": hist_binning(np.asarray(logs[600.0])),
        "elapsed_s": round(time.time() - t0, 1),
    }
    return out


# ---------------------------------------------------------------------------

class _MLBundle:
    """The estimators as the resolvers expect them: an object with
    ``.thermo`` (ThermoML) and ``.kinetics`` (KineticsML) attributes.

    KineticsML's constructor already builds a ThermoML for its covers()
    check - reuse it so the thermo checkpoint is loaded exactly once.
    """

    def __init__(self):
        self.kinetics = KineticsML()
        self.thermo = self.kinetics.thermo_ml


def main() -> int:
    t_start = time.time()
    ref_thermo = json.loads(THERMO_REF.read_text())
    ref_rxns = json.loads(RXN_REF.read_text())
    species_list = [
        {"smiles": smi, "label": v["label"], "in_ptl": v["in_ptl"],
         "class": v["class"]}
        for smi, v in ref_thermo["species"].items()
    ]

    print("[gate_04] loading estimators (real vendored checkpoints)...",
          flush=True)
    ml_bundle = _MLBundle()
    db = Databases.from_config({
        "thermo_libraries": THERMO_LIBRARIES,
        "reaction_libraries": REACTION_LIBRARIES,
    })

    print("[gate_04] check 4: checkpoint round-trip", flush=True)
    rt = check_roundtrip(ml_bundle.thermo.ckpt, ml_bundle.kinetics.ckpt)

    print(f"[gate_04] check 1/3 thermo: coverage + no-fallback "
          f"({len(species_list)} species)", flush=True)
    th = check_thermo(species_list, db.thermo, ml_bundle, ref_thermo)

    print(f"[gate_04] check 1/3 kinetics: coverage + no-fallback "
          f"({len(ref_rxns['reactions'])} reactions)", flush=True)
    ki = check_kinetics(ref_rxns, db.kinetics, ml_bundle)

    # --- verdict -----------------------------------------------------------
    checks = {
        "checkpoint_roundtrip": rt["pass"],
        "thermo_coverage": th["coverage"]["coverage_pct"] >= TH_COV_MIN,
        "kinetics_coverage": ki["coverage"]["coverage_pct"] >= KIN_COV_MIN,
        "no_fallback_thermo": (th["no_fallback"]["total"] == len(species_list)
                               and th["no_fallback"]["library_hits"]
                               + th["no_fallback"]["ml_hits"]
                               + th["no_fallback"]["coverage_errors"]
                               == th["no_fallback"]["total"]),
        "no_fallback_kinetics": (ki["no_fallback"]["total"] == len(
            ref_rxns["reactions"])
            and ki["no_fallback"]["library_hits"]
            + ki["no_fallback"]["ml_hits"]
            + ki["no_fallback"]["coverage_errors"]
            == ki["no_fallback"]["total"]),
    }
    acc_t = th["accuracy_ml_vs_legacy"]
    checks["accuracy_hf298"] = acc_t["dhf298_J_mol"].get("p95_abs", 0) \
        <= HERR_P95_MAX
    checks["accuracy_s298"] = acc_t["ds298_J_molK"].get("p95_abs", 0) \
        <= SERR_P95_MAX
    checks["accuracy_cp"] = acc_t["dcp_J_molK"].get("p95_abs", 0) \
        <= CPERR_P95_MAX
    for T in T_LIST:
        key = f"log10_k_ratio_{int(T)}"
        checks[f"accuracy_kT_{int(T)}"] = (
            ki["accuracy_ml_vs_legacy"][key].get("p95_abs", 0) <= KLOG_P95_MAX)

    overall = all(checks.values())
    results = {
        "gate": "job-04 thesis test (PoC premise: ML matches legacy accuracy)",
        "overall": "PASS" if overall else "RED",
        "checks": checks,
        "thresholds": {
            "thermo_coverage_min": TH_COV_MIN,
            "kinetics_coverage_min": KIN_COV_MIN,
            "hf298_p95_max_J_mol": HERR_P95_MAX,
            "s298_p95_max_J_molK": SERR_P95_MAX,
            "cp_p95_max_J_molK": CPERR_P95_MAX,
            "k_log10_p95_max": KLOG_P95_MAX,
        },
        "checkpoint_roundtrip": rt,
        "thermo": th,
        "kinetics": ki,
        "elapsed_s": round(time.time() - t_start, 1),
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(results, indent=2))

    # --- console summary ---------------------------------------------------
    print("\n" + "=" * 72)
    print(f"GATE 04 - THESIS TEST: {results['overall']}")
    print("=" * 72)
    for k, v in checks.items():
        print(f"  [{'ok' if v else 'XX'}] {k}")
    ct = rt
    print(f"  round-trip: thermo maxdiff {ct['thermo']['max_abs_diff_raw']:.2e}, "
          f"kinetics maxdiff {ct['kinetics']['max_abs_diff_raw']:.2e} "
          f"({ct['thermo']['pass'] and ct['kinetics']['pass']})")
    print(f"  thermo coverage: {th['coverage']['coverage_pct']:.1%} "
          f"(model {th['coverage']['model_covers']}/{len(species_list)}), "
          f"split {th['no_fallback']}")
    at = acc_t
    print(f"  accuracy (ML vs legacy): dHf298 p95 "
          f"{at['dhf298_kJ_mol']['p95_abs']:.1f} kJ/mol (max "
          f"{at['dhf298_kJ_mol']['max_abs']:.1f}), dS298 p95 "
          f"{at['ds298_J_molK']['p95_abs']:.1f} J/mol/K, dCp p95 "
          f"{at['dcp_J_molK']['p95_abs']:.1f} J/mol/K, N={at['dhf298_J_mol']['N']}")
    for s, v in at["dhf298_by_ref_sign_kJ_mol"].items():
        if v.get("N"):
            print(f"    dHf298 | {s}: N={v['N']} p95 {v['p95_abs']:.1f} "
                  f"kJ/mol mean {v['mean']:+.1f}")
    print(f"  kinetics coverage: {ki['coverage']['coverage_pct']:.1%} "
          f"(model {ki['coverage']['model_covers']}/{ki['n_reactions']}), "
          f"split {ki['no_fallback']}")
    for T in T_LIST:
        s = ki["accuracy_ml_vs_legacy"][f"log10_k_ratio_{int(T)}"]
        if s.get("N"):
            print(f"  k({int(T)}): p95 |log10 k ratio| {s['p95_abs']:.2f} "
                  f"(max {s['max_abs']:.2f}), mean {s['mean']:+.2f}, "
                  f"N={s['N']}")
    print(f"  results: {OUT}")
    print(f"  elapsed: {results['elapsed_s']}s")
    return 0 if overall else 2


if __name__ == "__main__":
    raise SystemExit(main())
