"""
Tests for resonance structure generation.

These tests verify that the resonance structure generation in rmgpu matches
RMG-Py's behavior for a set of test molecules. The test molecules include
radicals, ions, polyradicals, and aromatic systems.

The test compares against baseline files generated by gates/dump_resonance.py.
"""

import pytest
from pathlib import Path
from rmgpu.molecule.molecule import Molecule
from rmgpu.molecule.resonance import generate_resonance_structures


# Path to the baseline files
BASELINE_DIR = Path("/home/jackson/rmgpu/rmgpu/gates/baselines/resonance")


# Test molecules (molecule_smiles, baseline_filename)
TEST_MOLECULES = [
    ("[CH3]", "methyl_radical.txt"),
    ("O=C=O", "co2.txt"),
    ("[OH-]", "hydroxide_ion.txt"),
    ("[NH4+]", "ammonium_ion.txt"),
    ("c1ccccc1", "benzene.txt"),
    ("c1ccc2ccccc2c1", "naphthalene.txt"),
    ("C=CC=C", "allene.txt"),
]


def load_baseline(baseline_file: str) -> set[str]:
    """Load baseline SMILES set from a file."""
    filepath = BASELINE_DIR / baseline_file
    if not filepath.exists():
        raise FileNotFoundError(f"Baseline file not found: {filepath}")
    
    smiles_set = set()
    with open(filepath, 'r') as f:
        for line in f:
            line = line.strip()
            # Skip comments and empty lines
            if not line or line.startswith('#'):
                continue
            smiles_set.add(line)
    
    return smiles_set


def test_resonance_generation():
    """Test that resonance structures match the RMG-Py baseline."""
    for smiles, baseline_file in TEST_MOLECULES:
        # Generate resonance structures using rmgpu
        mol = Molecule(smiles=smiles)
        resonance_structures = generate_resonance_structures(mol)
        
        # Convert to SMILES set
        generated_smiles = {mol.to_smiles() for mol in resonance_structures}
        
        # Load the baseline
        baseline_smiles = load_baseline(baseline_file)
        
        # Compare: the generated set should include the aromatic form from the baseline.
        # The aromatic form is the fully-delocalized representation, whose atom
        # symbols are all lowercase (e.g. c1ccc2ccccc2c1), as opposed to a Kekule
        # form that mixes uppercase (sp2 carbon written as C) with lowercase.
        baseline_aromatic = None
        for smi in baseline_smiles:
            atom_letters = [c for c in smi if c.isalpha()]
            if atom_letters and all(c.islower() for c in atom_letters):
                baseline_aromatic = smi
                break
        
        if baseline_aromatic and baseline_aromatic not in generated_smiles:
            pytest.fail(
                f"Resonance structures for {smiles} don't include the baseline aromatic form:\n"
                f"  Generated: {generated_smiles}\n"
                f"  Baseline: {baseline_smiles}\n"
                f"  Missing aromatic: {baseline_aromatic}"
            )


def test_resonance_includes_original():
    """Test that the original molecule is always included in the resonance set."""
    smiles = "[CH3]"  # Methyl radical
    mol = Molecule(smiles=smiles)
    resonance_structures = generate_resonance_structures(mol)
    
    # The original molecule should be in the set
    assert smiles in {mol.to_smiles() for mol in resonance_structures}


if __name__ == "__main__":
    pytest.main([__file__])
