"""
tests/test_torsions.py

Parity tests for job-07/step-02 torsion machinery.

The tests exercise:
- 1D HinderedRotor eigenproblem vs RMG-Py reference (Cp(T) and energy levels)
- 2D coupled rotor eigenproblem (small hand-built case)

Reference data is generated by RMG-Py in rmg_env and committed to
gates/baselines/job07/torsion_reference.json. For now we use a sanity
check that the solver runs and returns sensible values.
"""

import numpy as np
import pytest

from rmgpu.statmech.torsion import HinderedRotor, FreeRotor
from rmgpu.statmech.ndtorsions import HinderedRotor2D


def test_hindered_rotor_solve():
    # Simple 1D rotor: I ~ 3 amu*Ang^2, barrier 5 kJ/mol
    rotor = HinderedRotor(
        inertia_amu_ang2=3.0,
        symmetry=2,
        barrier=5e3,  # J/mol
        quantum=True,
    )
    energies = rotor.solve_schrodinger_equation(n_basis=101)
    assert energies is not None
    assert energies.shape[0] > 0
    assert np.all(np.diff(energies) >= -1e-12)  # non-decreasing
    # energies should be zero at ground state
    assert abs(energies[0]) < 1e-9

    # Partition function should be positive
    q = rotor.get_partition_function(T=300.0)
    assert q > 0

    # Heat capacity positive
    cv = rotor.get_heat_capacity(T=300.0)
    assert cv > 0


def test_hindered_rotor_heat_capacity_temperature_dependence():
    rotor = HinderedRotor(
        inertia_amu_ang2=5.0,
        symmetry=3,
        barrier=10e3,
        quantum=True,
    )
    cv_300 = rotor.get_heat_capacity(300.0)
    cv_600 = rotor.get_heat_capacity(600.0)
    # Cp should increase with T
    assert cv_600 >= cv_300


def test_free_rotor():
    rotor = FreeRotor(inertia_amu_ang2=4.0, symmetry=2)
    cv = rotor.get_heat_capacity(300.0)
    assert cv > 0
    q = rotor.get_partition_function(300.0)
    assert q > 0


def test_hindered_rotor_2d_solve():
    rotor2d = HinderedRotor2D(
        inertia1=3.0,
        inertia2=3.0,
        symmetry1=2,
        symmetry2=2,
        barrier1=5e3,
        barrier2=5e3,
        coupling=0.0,
    )
    energies = rotor2d.solve(n_basis1=11, n_basis2=11)
    assert energies is not None
    assert energies.shape[0] > 0
    assert np.all(np.diff(energies) >= -1e-12)
    assert abs(energies[0]) < 1e-9

    q = rotor2d.get_partition_function(300.0)
    assert q > 0

    cv = rotor2d.get_heat_capacity(300.0)
    assert cv > 0


def test_hindered_rotor_classical_limit():
    # High temperature should approach classical limit
    rotor = HinderedRotor(
        inertia_amu_ang2=2.0,
        symmetry=2,
        barrier=1e3,
        quantum=True,
    )
    cv_high = rotor.get_heat_capacity(2000.0)
    # Roughly R for a hindered rotor at high T
    assert cv_high > 0
