"""
Family loader + KineticsFamilies facade (job-05/step-04).

Loads RMG's reaction-family definitions - templates, group trees, recipes,
and the reverse-family bookkeeping - and exposes the object the core loop
(job 06) asks for families, templates, and matching:

  - Family: one family's data - name, recipes (ReactionRecipe objects),
    templates (step-03's group tree: entries + top + forward_template,
    the shape core/template.py's match() consumes), rate rules (stored as
    DATA - see below), forbidden structures (as DATA), the reverse-family
    bookkeeping (reverse / reversible / own_reverse / reverse_map) and the
    effective reactant/product counts.
  - KineticsFamilies: loads all families of a named set (the 'default'
    recommended set) or a list of family names, and offers
    get_family(name), .families, match_reaction(reaction),
    get_families_of_reaction(reaction), and .blocked.

Source + the controlled parse
-----------------------------
Per the job-02 step-4 decision (reports/job-02-step-04-kineticsdb.md) the
family definitions ARE stored in rmgdb (kinetics_families_table: 129
families with template/recipe/reverse_map/reactant_num/product_num/
auto_generated; kinetics_family_groups_table: 8502 groups with their
adjacency lists; kinetics_family_rules_table). This loader's PRIMARY source
is therefore a controlled parse of the RMG-database family files
(<families>/<name>/groups.py, and rules.py for the rate-rule data):

  - groups.py carries EVERYTHING the loader needs - template(...),
    recipe(...), the bare flag assignments, entry(...) groups, the tree(...)
    hierarchy, and forbidden(...) structures - in RMG-Py's own file format.
    It is executed in a controlled namespace (the same mechanism rmgdb's own
    build and RMG-Py's Database.load use), so no DSL is re-invented.
  - rmgdb is used to CROSS-CHECK the parse: template/recipe/reverse_map/
    reactant_num/product_num/auto_generated must agree with the
    kinetics_families_table row, and every parsed group label/adjacency
    list must agree with the kinetics_family_groups_table row. Any
    disagreement is a load error (the two sources are built from the same
    files and must not drift).

Why the file parse is primary (documented finding, see
reports/job-05-step-04-families.md): rmgdb's
kinetics_family_groups_tree_table is INCOMPLETE. rmgdb's build.py derives
the parent/child edges with common/tree_str_to_pairs.sketchy_conversion,
which crashes (IndexError: pop from empty list) on several families'
tree() strings and build.py swallows the exception - so those families'
edges are missing (measured: H_Abstraction 0 of 534 edges;
R_Addition_MultipleBond 0 of 1211; 21 of the 51 default families have a
gap, several of them 0). The parent/child
hierarchy is what the tree descent (most-specific template labels) needs,
so the loader reconstructs it with RMG-Py's own _load_tree semantics
(rmgpy/data/base.py: parent = parents[level-1]; top = no parent, in
first-appearance order) from the tree() string - verified 0 mismatches
against the step-03 recorded reference trees (H_Abstraction 536 nodes,
intra_H_migration 313, Intra_ene_reaction 29, R_Addition_MultipleBond's
real-DB subset).

Rate rules are DATA
-------------------
rules.py is parsed and attached to Family.rules as plain dicts (label,
rank, reversible, elementary_high_p, duplicate, the kinetics object's
type name + raw args). The RATE-RULE ESTIMATOR is deleted (PLAN 3 / PLAN
4: ML is the only estimator) - nothing in this module computes a rate
from the rules; they are stored for the depository/reverse-rate purposes
of job 08.

Blocked families
----------------
A family whose data format the loader cannot express goes to
KineticsFamilies.blocked ({name: {reason, construct, note}}) instead of
Family. The list is load-bearing for job 06 (it proceeds around them); it
is expected to stay empty for the 'default' set (validated in
tests/test_families.py against the recorded reference).
"""

import ast
import importlib
import importlib.machinery
import importlib.util
import os
import re
import sqlite3
from pathlib import Path

from rmgpu.molecule.group import Group
from rmgpu.core.recipe import ReactionRecipe
from rmgpu.core import template as tmpl

# ---------------------------------------------------------------------------
# Defaults: RMG-database location + rmgdb cross-check DB
# ---------------------------------------------------------------------------

DEFAULT_FAMILIES_DIR = Path('/home/jackson/rmgpu/RMG-database/input/kinetics'
                            '/families')
DEFAULT_KINETICS_DB = Path('/home/jackson/rmgpu/rmgdb/db/kinetics.db')

# The bare assignments a family file may carry (RMG-Py family.py local_
# context defaults, KineticsFamily.load).
_FLAG_KEYS = ('reversible', 'reverse', 'reverseMap', 'reactantNum',
              'productNum', 'autoGenerated', 'allowChargedSpecies',
              'electrons', 'boundaryAtoms', 'treeDistances')

# Logic-node string detection (RMG KineticsGroups.load_entry).
_LOGIC_RE = re.compile(r'(?i)^\s*(NOT\s)?\s*(OR|AND|UNION)\s*\{')


class FamilyLoadError(Exception):
    """A family's data cannot be loaded or cross-checked."""


# ---------------------------------------------------------------------------
# Controlled parse of the family files
# ---------------------------------------------------------------------------

def _parse_groups_file(path):
    """Execute one family's groups.py in a controlled namespace and return
    its raw data: template/recipe kwargs, the bare flag assignments, the
    entry(...) groups (file order), the tree(...) string, and the
    forbidden(...) structures. Raises FamilyLoadError on any exec failure."""
    cap = {
        'entries': [],          # [{index,label,group}] file order
        'template': None,
        'recipe': None,
        'tree': None,
        'forbidden': [],
        'flags': {},
    }

    def entry(*, index=None, label='', group='', kinetics=None, **kw):
        cap['entries'].append({'index': index, 'label': label,
                               'group': group})

    def template(**kw):
        cap['template'] = kw

    def recipe(**kw):
        cap['recipe'] = kw

    def tree(s):
        cap['tree'] = s

    def forbidden(**kw):
        cap['forbidden'].append(dict(kw))

    env = {'entry': entry, 'template': template, 'recipe': recipe,
           'tree': tree, 'forbidden': forbidden,
           'True': True, 'False': False, 'None': None}
    try:
        g = dict(env)
        with open(path) as f:
            src = f.read()
        exec(compile(src, str(path), 'exec'), g)
    except Exception as e:
        raise FamilyLoadError('groups.py exec failed for %s: %s: %s'
                              % (path, type(e).__name__, e))
    cap['flags'] = {k: g[k] for k in _FLAG_KEYS if k in g}
    for k in cap['flags']:
        pass  # (flags captured above; names kept in _FLAG_KEYS)
    return cap


def _parse_rules_file(path):
    """Execute one family's rules.py in a controlled namespace and return
    the rate rules as plain DATA: [{index, label, rank, reversible,
    elementary_high_p, duplicate, kinetics_kind, kinetics_args}]. The
    kinetics object is captured by name + raw constructor args - it is
    stored, never evaluated (the rate-rule estimator is deleted, PLAN 3)."""
    rules = []

    class _KineticsStub:
        def __init__(self, *args, **kwargs):
            self.args = args
            self.kwargs = kwargs

    names = ['Arrhenius', 'ArrheniusEP', 'ArrheniusBM', 'PDepArrhenius',
             'MultiPDepArrhenius', 'Lindemann', 'Troe', 'ThirdBody',
             'MultiArrhenius', 'Chebyshev', 'Marcus', 'KineticsData',
             'SurfaceArrhenius', 'SurfaceArrheniusBEP',
             'SurfaceChargeTransfer', 'ArrheniusChargeTransfer',
             'ArrheniusChargeTransferBM', 'StickingCoefficient',
             'StickingCoefficientBEP']
    stubs = {n: type(n, (_KineticsStub,), {}) for n in names}

    # RateUncertainty is nested inside ArrheniusBM's uncertainty= kwarg in
    # rules.py; the stub captures its raw args so the rule stays DATA (it is
    # never evaluated - the rate-rule estimator is deleted).
    class _RateUncertaintyStub(_KineticsStub):
        pass
    stubs['RateUncertainty'] = _RateUncertaintyStub

    def entry(*, index=None, label='', kinetics=None, shortDesc='',
              longDesc='', rank=None, allow_max_rate_violation=None,
              reversible=None, elementary_high_p=None, duplicate=None,
              **kw):
        rules.append({
            'index': index,
            'label': label,
            'rank': rank,
            'reversible': reversible,
            'elementary_high_p': elementary_high_p,
            'duplicate': duplicate,
            'kinetics_kind': type(kinetics).__name__ if kinetics else None,
            'kinetics_args': (getattr(kinetics, 'args', None),
                              getattr(kinetics, 'kwargs', None))
            if kinetics else None,
        })

    env = {'entry': entry}
    env.update(stubs)
    env['R'] = 8.314472  # RMG-Py constants.R (rate rules store raw data;
    # the value only matters if a constructor evaluates - they do not)
    env['True'] = True
    env['False'] = False
    env['None'] = None
    try:
        g = dict(env)
        with open(path) as f:
            src = f.read()
        exec(compile(src, str(path), 'exec'), g)
    except Exception:
        return None  # rules are data for job 08; a parse gap is recorded
                     # on the family (rules_error), not fatal
    return rules


def _load_tree(tree_str):
    """RMG-Py Database._load_tree (rmgpy/data/base.py), ported. Returns
    (children, parent, top):
      children: {label: [child labels]} (file order, parent->child order)
      parent:   {label: parent label or None}
      top:      labels with no parent, in first-appearance order.
    Faithful to RMG: parent = parents[level-1]; level must not exceed the
    stack depth (RMG raises DatabaseError on that); blank/comment lines
    are skipped. Comment stripping matches RMG's remove_comment_from_line
    (base.py) EXACTLY: only a C++-style '//' comment is cut. '#' is a
    legitimate character in tree labels (e.g. 'C_rad/H2/Cs\\H2\\Cs|Cs#O'),
    so it is NOT treated as a comment marker here."""
    parser = re.compile(r'^\s*L(?P<level>\d+)\s*:\s*(?P<label>\S+)')
    children = {}
    parent = {}
    top = []
    parents = [None]
    for raw in tree_str.splitlines():
        # RMG remove_comment_from_line: cut at the first '//'
        i = raw.find('//')
        line = (raw[:i] if i >= 0 else raw).strip()
        if not line:
            continue
        m = parser.match(line)
        if not m:
            raise FamilyLoadError("Couldn't parse tree line '%s'" % line)
        level = int(m.group('level'))
        label = m.group('label')
        if len(parents) < level:
            raise FamilyLoadError(
                'Invalid level %d in tree line %r' % (level, line))
        while len(parents) > level:
            parents.pop()
        par = parents[level - 1] if len(parents) > 0 else None
        if par is not None:
            children.setdefault(par, []).append(label)
            parent[label] = par
        else:
            top.append(label)
            parent[label] = None
        parents.append(label)
    return children, parent, top


# ---------------------------------------------------------------------------
# Family
# ---------------------------------------------------------------------------

class Family(object):
    """One reaction family's data (RMG-Py KineticsFamily's
    enumeration/matching subset, minus the deleted rate-rule estimator).

    Fields consumed by core/template.py's match() (it takes this object
    directly - it has the TemplateFamily shape):
      - label, entries, top, forward_template, reactant_num, recipe,
        reverse_recipe, own_reverse, reversible, allow_charged_species,
        electrons, product_num_forward, reverse_map
    Facade-only fields:
      - name, short_desc, long_desc: identity
      - reverse: the reverse family's name (RMG self.reverse; None for
        own-reverse families)
      - rules: the parsed rate rules as DATA (list of dicts) or None
      - forbidden: the parsed forbidden structures as DATA (list of
        {label, group} dicts)
      - tree_distances, boundary_atoms: RMG's stored values (data)
    """

    # -- TemplateFamily-compatible shape (core/template.py match()) ----
    label = ''
    entries = None        # {label: TemplateEntry}
    top = None            # [TemplateEntry] (tree top nodes, file order)
    forward_template = None  # [TemplateEntry] (template reactant slots)
    reactant_num = 1
    recipe = None
    reverse_recipe = None
    own_reverse = False
    reversible = False
    allow_charged_species = False
    electrons = 0
    product_num_forward = None
    reverse_map = None

    # -- facade fields -------------------------------------------------
    name = ''
    short_desc = ''
    long_desc = ''
    reverse = None
    rules = None
    rules_error = None
    forbidden = None
    tree_distances = None
    boundary_atoms = None
    auto_generated = False
    reactant_num_stored = None
    num_template_reactants_effective = None  # split() count (count parity only)
    product_num_stored = None
    template_products = None  # [entry labels] (the template's products)
    num_groups_file = 0       # entry(...) count in groups.py

    def __init__(self, name):
        self.label = name
        self.name = name

    def __repr__(self):
        return '<Family %s>' % self.label

    # ------------------------------------------------------------------
    # Construction from the controlled parse (+ rmgdb cross-check)
    # ------------------------------------------------------------------

    @classmethod
    def from_files(cls, name, fam_dir, kinetics_db=None):
        """Build a Family from <fam_dir>/<name>/groups.py (+ rules.py),
        cross-checking against the rmgdb kinetics_families_table /
        kinetics_family_groups_table rows when `kinetics_db` is given.
        Raises FamilyLoadError on a missing file, a parse failure, or a
        cross-check disagreement."""
        fam_path = Path(fam_dir) / name
        groups_path = fam_path / 'groups.py'
        if not groups_path.exists():
            raise FamilyLoadError('no groups.py for family %s at %s'
                                  % (name, fam_path))
        cap = _parse_groups_file(groups_path)
        if cap['template'] is None or 'reactants' not in cap['template']:
            raise FamilyLoadError('family %s: no template() declaration'
                                  % name)
        if cap['recipe'] is None or 'actions' not in cap['recipe']:
            raise FamilyLoadError('family %s: no recipe() declaration'
                                  % name)
        if cap['tree'] is None:
            raise FamilyLoadError('family %s: no tree() declaration' % name)
        entries_file = cap['entries']
        if not entries_file:
            raise FamilyLoadError('family %s: no entry() declarations'
                                  % name)

        # ---- rmgdb cross-check (the job-02 step-4 storage decision) --
        descriptions = None
        if kinetics_db is not None:
            descriptions = _cross_check_rmgdb(name, cap, kinetics_db)

        # ---- group tree (RMG-Py _load_tree semantics) ---------------
        children, parent, top_labels = _load_tree(cap['tree'])
        entry_labels = [e['label'] for e in entries_file]
        label_set = set(entry_labels)
        for lab in top_labels:
            if lab not in label_set:
                raise FamilyLoadError(
                    'family %s: tree top %r has no entry' % (name, lab))
        for par, kids in children.items():
            if par not in label_set:
                raise FamilyLoadError(
                    'family %s: tree parent %r has no entry' % (name, par))
            for c in kids:
                if c not in label_set:
                    raise FamilyLoadError(
                        'family %s: tree child %r has no entry' %
                        (name, c))

        # ---- entries: group / logic node ----------------------------
        entries = {}
        for e in entries_file:
            gtxt = e['group']
            if _LOGIC_RE.match(gtxt or ''):
                entries[e['label']] = tmpl.TemplateEntry(
                    e['label'], _make_logic_node(gtxt))
            else:
                try:
                    g = Group().parse(gtxt)
                except Exception as ex:
                    raise FamilyLoadError(
                        'family %s: group %r unparseable: %s: %s' %
                        (name, e['label'], type(ex).__name__, ex))
                entries[e['label']] = tmpl.TemplateEntry(e['label'], g)

        top = [entries[t] for t in top_labels]
        for e in entries.values():
            par = parent.get(e.label)
            e.parent = entries[par] if par else None
            e.children = [entries[c] for c in children.get(e.label, [])]

        # ---- recipe / reverse recipe --------------------------------
        recipe = ReactionRecipe.from_data([list(a) for a in
                                           cap['recipe']['actions']])
        reverse_recipe = recipe.get_reverse()  # RMG forward_recipe.get_reverse()

        # ---- flags (RMG KineticsFamily.load local_context defaults) --
        flags = cap['flags']
        template_kw = cap['template']
        own_reverse = bool(template_kw.get('ownReverse', False))
        if own_reverse:
            reverse = None
            reversible = True
        else:
            reverse = flags.get('reverse', None)
            if reverse is None:
                reverse = '%s_reverse' % name  # RMG's load default
            if reverse == name:
                reverse = None
            rev = flags.get('reversible', None)
            reversible = True if rev is None else bool(rev)
        reverse_map = flags.get('reverseMap', None)
        product_num = flags.get('productNum', None)
        allow_charged = bool(flags.get('allowChargedSpecies', False))
        electrons = int(flags.get('electrons', 0))
        auto_generated = bool(flags.get('autoGenerated', False))

        fwd_template_labels = list(template_kw['reactants'])
        for lab in fwd_template_labels:
            if lab not in entries:
                raise FamilyLoadError(
                    'family %s: template reactant %r has no group entry'
                    % (name, lab))

        # ---- reactant count: the stored flag (RMG fam.reactant_num) ----
        # The matcher's count guard (match()'s `len(reactants) != fam.reactant_num`
        # and the auto_generated guard in RMG get_labeled_reactants_and_products)
        # reads RMG's OWN fam.reactant_num, which is the stored reactantNum flag
        # when present, else the number of template reactant slots. We mirror
        # that exactly:
        #   R_Recombination     reactantNum=2      -> 2 (accept 2 reactants;
        #                                              single-group split path)
        #   Birad_recombination reactantNum=1,
        #                          autoGenerated=1 -> 1  (RMG's auto_generated
        #                                              guard then REJECTS the
        #                                              2-radical recombination
        #                                              reactions - they belong
        #                                              to R_Recombination)
        #   R_Addition_MultipleBond (no reactantNum,
        #                          2 template slots) -> 2
        # We also record the separate "effective reactant count after the
        # single-group split" (RMG's item.split() on the one-group case) in
        # num_template_reactants_effective, which the step-04 reference records
        # as num_template_reactants_effective - used for count parity only, NOT
        # by the matcher.
        reactant_num_stored = flags.get('reactantNum', None)
        reactant_num = (reactant_num_stored
                        if reactant_num_stored is not None
                        else len(fwd_template_labels))
        reactant_num_eff = len(fwd_template_labels)
        if len(fwd_template_labels) == 1:
            item = entries[fwd_template_labels[0]].item
            if isinstance(item, Group):
                reactant_num_eff = len(item.split())

        # ---- product count (RMG effective forward product count) ----
        product_num_forward = (product_num
                               if product_num is not None
                               else len(template_kw.get('products', [])))

        fam = cls(name)
        fam.entries = entries
        fam.top = top
        fam.forward_template = [entries[t] for t in fwd_template_labels]
        fam.template_products = list(template_kw.get('products', []))
        fam.reactant_num = reactant_num
        fam.num_template_reactants_effective = reactant_num_eff
        fam.recipe = recipe
        fam.reverse_recipe = reverse_recipe
        fam.own_reverse = own_reverse
        fam.reversible = reversible
        fam.allow_charged_species = allow_charged
        fam.electrons = electrons
        fam.product_num_forward = product_num_forward
        fam.reverse_map = reverse_map
        fam.reverse = reverse
        fam.auto_generated = auto_generated
        fam.reactant_num_stored = reactant_num_stored
        fam.product_num_stored = product_num
        fam.tree_distances = flags.get('treeDistances', None)
        fam.boundary_atoms = flags.get('boundaryAtoms', None)
        if descriptions is not None:
            fam.short_desc, fam.long_desc = descriptions
        fam.short_desc = fam.short_desc or ''
        fam.long_desc = fam.long_desc or ''
        fam.forbidden = [
            {'label': fb.get('label', ''), 'group': fb.get('group', '')}
            for fb in cap['forbidden']
        ]
        fam.num_groups_file = len(entries_file)

        # ---- rate rules (DATA, for job 08; the estimator is deleted) -
        rules_path = fam_path / 'rules.py'
        if rules_path.exists():
            rules = _parse_rules_file(rules_path)
            if rules is None:
                fam.rules_error = 'rules.py parse failed (data-only gap)'
            else:
                fam.rules = rules
        return fam


def _cross_check_rmgdb(name, cap, db_path):
    """Verify the controlled parse against the rmgdb tables (the
    job-02 step-4 storage decision). Compares: the family row's
    template/recipe/reversible/reverse_map/reactant_num/product_num/
    auto_generated, and every group's adjacency list (label -> group).
    Raises FamilyLoadError on any disagreement."""
    with sqlite3.connect(db_path) as conn:
        cur = conn.cursor()
        cur.execute('SELECT template, recipe, reversible, reverse_map, '
                    'reactant_num, product_num, auto_generated, '
                    'short_description, long_description '
                    'FROM kinetics_families_table WHERE name = ?', (name,))
        row = cur.fetchone()
        if row is None:
            raise FamilyLoadError(
                'family %s missing from rmgdb kinetics_families_table'
                % name)
        (tpl, rcp, rev, rmap, rn, pn, ag, sd, ld) = row
        got_tpl = ast.literal_eval(tpl)
        want_tpl = {'reactants': cap['template']['reactants'],
                    'products': cap['template'].get('products', []),
                    'ownReverse': bool(cap['template'].get('ownReverse',
                                                           False))}
        if got_tpl != want_tpl:
            raise FamilyLoadError('family %s: template mismatch rmgdb %r '
                                  'vs file %r' % (name, got_tpl, want_tpl))
        got_rcp = ast.literal_eval(rcp)
        want_rcp = {'actions': [list(a) for a in cap['recipe']['actions']]}
        if got_rcp != want_rcp:
            raise FamilyLoadError('family %s: recipe mismatch rmgdb %r '
                                  'vs file %r' % (name, got_rcp, want_rcp))
        if bool(rev) != bool(cap['flags'].get('reversible', True)):
            raise FamilyLoadError(
                'family %s: reversible mismatch rmgdb %r vs file %r'
                % (name, rev, cap['flags'].get('reversible', True)))
        got_rmap = ast.literal_eval(rmap) if rmap else {}
        want_rmap = cap['flags'].get('reverseMap') or {}
        if got_rmap != want_rmap:
            raise FamilyLoadError(
                'family %s: reverse_map mismatch rmgdb %r vs file %r'
                % (name, got_rmap, want_rmap))
        if bool(ag) != bool(cap['flags'].get('autoGenerated', False)):
            raise FamilyLoadError(
                'family %s: auto_generated mismatch' % name)
        if rn is not None and rn != cap['flags'].get('reactantNum'):
            raise FamilyLoadError(
                'family %s: reactant_num mismatch rmgdb %r vs file %r'
                % (name, rn, cap['flags'].get('reactantNum')))
        if pn is not None and pn != cap['flags'].get('productNum'):
            raise FamilyLoadError(
                'family %s: product_num mismatch rmgdb %r vs file %r'
                % (name, pn, cap['flags'].get('productNum')))
        # group adjacency lists (label -> group), all of them
        cur.execute(
            'SELECT label, group_adj_list FROM kinetics_family_groups_table '
            'WHERE family_id = (SELECT id FROM kinetics_families_table '
            'WHERE name = ?)', (name,))
        db_groups = {label: adj for label, adj in cur.fetchall()}
        file_groups = {e['label']: e['group'] for e in cap['entries']}
        if set(db_groups) != set(file_groups):
            raise FamilyLoadError(
                'family %s: group label set mismatch rmgdb %d vs file %d'
                % (name, len(db_groups), len(file_groups)))
        for lab, adj in file_groups.items():
            if (db_groups[lab] or '') != (adj or ''):
                raise FamilyLoadError(
                    'family %s: group %r adjacency mismatch' % (name, lab))
    return sd, ld


def _make_logic_node(text):
    """RMG make_logic_node (rmgpy/data/base.py), ported onto the
    step-03 LogicNode (symbol/components/invert). The real database uses
    OR{...} only (verified: no AND{ / NOT OR{ / NOT AND{ in any
    families/groups.py), but AND/UNION/NOT are handled for completeness.
    Nested logic nodes appear only as entry labels in the real DB - the
    component strings are entry labels here."""
    m = _LOGIC_RE.match(text)
    if not m:
        raise FamilyLoadError('not a logic node: %r' % text[:40])
    invert = bool(m.group(1))
    symbol = 'OR' if m.group(2).upper() in ('OR', 'UNION') else 'AND'
    contents = text[m.end() - 1:]  # from the '{'
    if not (contents.startswith('{') and contents.endswith('}')):
        raise FamilyLoadError('unbalanced logic node: %r' % text[:40])
    contents = contents[1:-1]
    items = []
    chars = []
    depth = 0
    for ch in contents:
        if ch == '{':
            depth += 1
        elif ch == '}':
            depth -= 1
        if ch == ',' and depth == 0:
            items.append(''.join(chars).strip())
            chars = []
        else:
            chars.append(ch)
    if chars:
        items.append(''.join(chars).strip())
    if depth != 0:
        raise FamilyLoadError('unbalanced braces in logic node: %r'
                              % text[:40])
    return tmpl.LogicNode(symbol, items, invert)


# ---------------------------------------------------------------------------
# KineticsFamilies (the facade)
# ---------------------------------------------------------------------------

class KineticsFamilies(object):
    """Loads a set of families and answers the core loop's questions.

    API:
      - families: list of Family (load order: sorted names)
      - get_family(name) -> Family (KeyError if not loaded)
      - match_reaction(reaction) -> (family, template_labels) or
        (None, None): the family whose templates describe the reaction
        (delegates to core/template.py's match; the reaction must have
        .reactants/.products - e.g. core.template.Reaction)
      - get_families_of_reaction(reaction) -> [Family] (every loaded
        family that matches; RMG's core loop iterates families in order
        and the first match wins for attribution - see match_reaction)
      - default_set: the loaded family-name set
      - blocked: {name: {reason, construct, note}} - families whose data
        format the loader cannot express (job 06 proceeds around them)
    """

    def __init__(self, fam_dir=DEFAULT_FAMILIES_DIR,
                 kinetics_db=DEFAULT_KINETICS_DB):
        self.fam_dir = Path(fam_dir)
        self.kinetics_db = Path(kinetics_db) if kinetics_db else None
        self._families = {}
        self.blocked = {}
        self.default_set = set()
        self.families = []

    # ------------------------------------------------------------------

    def load(self, families='default'):
        """Load a family set: 'default' (RMG-database recommended.py's
        `default` set), 'all' (every family directory), or a list of
        family names. Returns self."""
        if families == 'all':
            names = sorted(d.name for d in self.fam_dir.iterdir()
                           if d.is_dir() and d.name != '__pycache__')
        elif isinstance(families, str) and families in self._recommended():
            names = sorted(self._recommended()[families])
        else:
            if isinstance(families, str):
                families = [families]
            names = list(families)
        self.default_set = set(names)
        self._families = {}
        self.families = []
        self.blocked = {}
        for name in names:
            try:
                fam = Family.from_files(name, self.fam_dir,
                                        self.kinetics_db)
                self._families[name] = fam
                self.families.append(fam)
            except FamilyLoadError as e:
                self.blocked[name] = {
                    'reason': str(e),
                    'construct': 'groups.py parse / rmgdb cross-check',
                    'note': 'job 06 proceeds around this family',
                }
        return self

    def _recommended(self):
        """RMG-database families/recommended.py's named sets (exec'd,
        same source of truth RMG-Py's load_recommended_families uses)."""
        path = self.fam_dir / 'recommended.py'
        loader = importlib.machinery.SourceFileLoader('rec', str(path))
        spec = importlib.util.spec_from_file_location('rec', str(path),
                                                      loader=loader)
        rec = importlib.util.module_from_spec(spec)
        loader.exec_module(rec)
        return {k: v for k, v in rec.__dict__.items()
                if not k.startswith('_') and isinstance(v, set)}

    # ------------------------------------------------------------------

    def get_family(self, name):
        if name not in self._families:
            raise KeyError('family %r not loaded (blocked: %s)'
                           % (name, name in self.blocked))
        return self._families[name]

    def match_reaction(self, reaction):
        """The family attribution for `reaction` (RMG core-loop semantics:
        families are tried in load order - sorted name order here - and
        the first whose templates describe the reaction wins). Returns
        (family, template_labels) or (None, None)."""
        for fam in self.families:
            labels = tmpl.match(fam, reaction)
            if labels is not None:
                return fam, labels
        return None, None

    def get_families_of_reaction(self, reaction):
        """Every loaded family whose templates describe `reaction`
        (no first-match cutoff)."""
        out = []
        for fam in self.families:
            if tmpl.match(fam, reaction) is not None:
                out.append(fam)
        return out

    def __len__(self):
        return len(self.families)

    def __iter__(self):
        return iter(self.families)

    def __repr__(self):
        return '<KineticsFamilies %d families, %d blocked>' % (
            len(self.families), len(self.blocked))
