"""
Filtration of resonance structures, ported from RMG-Py (rmgpy/molecule/
filtration.py).

Given the full list of resonance structures generated by the shift rules, this
module keeps only the representative ones, by:
  1. minimizing overall deviation from the octet rule
  2. allowing a +1 charge span only when it introduces a new radical site or
     a new multiple bond
  3. stabilizing charge by electronegativity (negative charge on the more
     electronegative atom) and by proximity (opposite charges as close as
     possible)
  4. guaranteeing the input structure is present in the result

All quantities are computed from rmgpu's RDKit-based Molecule using the same
definitions RMG-Py uses (octet deviation, charge span).
"""
from collections import deque

from rdkit import Chem
from rmgpu.molecule.molecule import Molecule

# Electronegativity (Pauling), a subset of RMG-Py's PeriodicSystem table,
# covering the elements present in the job-01 test set plus common neighbors.
ELECTRONEGATIVITY = {
    'H': 2.20, 'C': 2.55, 'N': 3.04, 'O': 3.44, 'F': 3.98,
    'Si': 1.90, 'P': 2.19, 'S': 2.58, 'Cl': 3.16, 'Br': 2.96, 'I': 2.66,
    'B': 2.04, 'Li': 0.98, 'Na': 0.93,
}

_VAL_ELECTRONS = {
    'C': 4, 'N': 5, 'O': 6, 'F': 7, 'Si': 4, 'P': 5, 'S': 6,
    'Cl': 7, 'Br': 7, 'I': 7, 'B': 3,
}


def _bond_order(bond):
    """Integer bond order for octet-deviation purposes (aromatic -> 1)."""
    bt = bond.GetBondTypeAsDouble()
    if abs(bt - 1.5) < 0.01:
        return 1
    return int(round(bt))


def _atom_lone_pairs(atom):
    """Lone pairs on a RDKit atom via RMG's valence formula."""
    if atom.GetSymbol() in ('H', 'Li'):
        return 0
    ve = _VAL_ELECTRONS.get(atom.GetSymbol())
    if ve is None:
        return 0
    bond_order = sum(_bond_order(b) for b in atom.GetBonds())
    lp = (ve - atom.GetNumRadicalElectrons() - atom.GetFormalCharge() - bond_order) // 2
    return max(0, lp)


def get_octet_deviation(mol, allow_expanded_octet=True):
    """
    Octet deviation for a Molecule, per RMG-Py filtration.get_octet_deviation.
    Summed over non-H, non-Li atoms: |8 - valence_electrons|, where
    valence_electrons = 2*(bond_order + lone_pairs) + radical_electrons.
    A birad site that would substitute a lone pair adds a +3 penalty.
    """
    deviation = 0
    for atom in mol._rdkit.GetAtoms():
        sym = atom.GetSymbol()
        if sym in ('H', 'Li'):
            continue
        bond_order = sum(_bond_order(b) for b in atom.GetBonds())
        lone_pairs = _atom_lone_pairs(atom)
        radical = atom.GetNumRadicalElectrons()
        val_electrons = 2 * (bond_order + lone_pairs) + radical
        if sym in ('C', 'N', 'O'):
            deviation += abs(8 - val_electrons)
        elif sym == 'S':
            if not allow_expanded_octet:
                deviation += abs(8 - val_electrons)
            else:
                if lone_pairs <= 1:
                    deviation += min(abs(8 - val_electrons),
                                     abs(10 - val_electrons),
                                     abs(12 - val_electrons))
                else:
                    deviation += abs(8 - val_electrons)
            for bond in atom.GetBonds():
                if bond.GetOtherAtom(atom).GetSymbol() == 'S' and bond.GetBondTypeAsDouble() == 3:
                    deviation += 0.5
        # Birad penalty
        if radical >= 2 and ((sym == 'N' and lone_pairs == 0)
                             or (sym == 'O' and lone_pairs in (0, 1, 2))
                             or (sym == 'S' and lone_pairs in (0, 1, 2))):
            deviation += 3
    return deviation


def get_octet_deviation_list(mol_list, allow_expanded_octet=True):
    return [get_octet_deviation(m, allow_expanded_octet) for m in mol_list]


def get_charge_span(mol):
    """Charge span: (sum |charge| - |net charge|) / 2, per RMG-Py."""
    net = mol.get_charge()
    sum_abs = sum(abs(a.GetFormalCharge()) for a in mol._rdkit.GetAtoms())
    return (sum_abs - abs(net)) / 2


def get_charge_span_list(mol_list):
    return [get_charge_span(m) for m in mol_list]


def _shortest_path_length(mol, i, j):
    """Number of atoms in the shortest path between atom i and atom j (RDKit)."""
    rdmol = mol._rdkit
    if i == j:
        return 1
    path = Chem.GetShortestPath(rdmol, i, j)
    return len(path) if path else 999


def _radical_sites(mol):
    return tuple(sorted(a.GetIdx() for a in mol._rdkit.GetAtoms()
                        if a.GetNumRadicalElectrons() > 0))


def _multipole_bond_sites(mol):
    """Tuples (i<j) of double/triple bonded atoms."""
    sites = set()
    for b in mol._rdkit.GetBonds():
        if b.GetBondTypeAsDouble() in (2.0, 3.0):
            sites.add((min(b.GetBeginAtomIdx(), b.GetEndAtomIdx()),
                       max(b.GetBeginAtomIdx(), b.GetEndAtomIdx())))
    return tuple(sorted(sites))


def _is_isomorphic(a, b):
    return a.is_isomorph(b)


def _structural_key(mol):
    """A positional, bond-order-sensitive structural key for a resonance form.

    Delegates to ``resonance._form_key`` (the single source of truth): the exact
    bond-order signature on the STORED mol, with aromatic-flagged bonds
    normalized to 1.5, plus per-atom (symbol, radical, charge).

    This mirrors RMG's `is_identical` (positional, bond-order-sensitive) rather
    than the canonical SMILES: it keeps isomorphic-but-not-identical forms as
    distinct - the two ortho benzylic radicals (same canonical SMILES, different
    radical POSITION) and the aromatic representative vs its kekulized variant
    (same canonical SMILES, different ring bond orders). This is exactly the
    `keep_isomorphic=True` behavior RMG's `generate_resonance_structures` uses,
    which is what job-05's Intra_ene parity needs (the 5-form 1-phenylethyl set)
    AND the job-01 benzene/toluene aromatic+kek pair.
    """
    from rmgpu.molecule.resonance import _form_key
    return _form_key(mol)


def octet_filtration(mol_list, octet_deviation_list):
    min_dev = min(octet_deviation_list)
    filtered = []
    charge_spans = []
    for m, dev in zip(mol_list, octet_deviation_list):
        if dev == min_dev:
            filtered.append(m)
            charge_spans.append(get_charge_span(m))
    return filtered, charge_spans


def stabilize_charges_by_electronegativity(mol_list, allow_empty_list=False):
    """Keep only structures that obey the electronegativity rule."""
    keep = []
    for m in mol_list:
        pos = neg = 0.0
        for a in m._rdkit.GetAtoms():
            ch = a.GetFormalCharge()
            en = ELECTRONEGATIVITY.get(a.GetSymbol(), 0.0)
            if ch > 0:
                pos += en * abs(ch)
                if a.GetSymbol() == 'O':
                    # penalty for O+ not adjacent to F-
                    if not any(b.GetOtherAtom(a).GetSymbol() == 'F'
                               and b.GetOtherAtom(a).GetFormalCharge() < 0
                               for b in a.GetBonds()):
                        pos += 1
            elif ch < 0:
                neg += en * abs(ch)
        if pos > neg:
            continue  # drop
        keep.append(m)
    if keep or allow_empty_list:
        return keep
    return list(mol_list)


def stabilize_charges_by_proximity(mol_list):
    """Keep only structures that obey the charge-proximity rule."""
    if not mol_list:
        return mol_list
    # Cumulative opposite/similar charge distances per structure
    dists = []
    for m in mol_list:
        opp = sim = 0
        charged = [a.GetIdx() for a in m._rdkit.GetAtoms() if a.GetFormalCharge() != 0]
        for x in range(len(charged)):
            for y in range(x + 1, len(charged)):
                a1 = m._rdkit.GetAtomWithIdx(charged[x])
                a2 = m._rdkit.GetAtomWithIdx(charged[y])
                d = _shortest_path_length(m, charged[x], charged[y])
                if (a1.GetFormalCharge() > 0) ^ (a2.GetFormalCharge() > 0):
                    opp += d
                else:
                    sim += d
        dists.append((opp, sim))
    min_opp = min(d[0] for d in dists)
    to_keep_idx = [i for i, d in enumerate(dists) if d[0] <= min_opp]
    # Among those, keep the max similar-charge distance group
    max_sim = max(d[1] for i, d in enumerate(dists) if i in to_keep_idx)
    to_keep_idx = [i for i in to_keep_idx if dists[i][1] >= max_sim - 1e-9]
    return [m for i, m in enumerate(mol_list) if i in to_keep_idx]


def _find_unique_sites_in_charged_list(mol, rad_sites, mul_sites):
    """Return [mol] if it has a new radical site or a new multiple bond."""
    mol_rad = _radical_sites(mol)
    for s in mol_rad:
        if s not in rad_sites:
            return [mol]
    mol_mul = _multipole_bond_sites(mol)
    for s in mol_mul:
        if s not in mul_sites:
            return [mol]
    return []


def charge_filtration(filtered_list, charge_span_list):
    """Port of RMG-Py charge_filtration (see module docstring for the rules)."""
    min_span = min(charge_span_list)
    if len(set(charge_span_list)) > 1:
        charged_list = [m for m, s in zip(filtered_list, charge_span_list)
                        if s == min_span + 1]
        filtered_list = [m for m, s in zip(filtered_list, charge_span_list)
                         if s == min_span]
        # Radical + multiple-bond sites in the (lowest-span) filtered list
        rad_sites = set()
        mul_sites = set()
        for m in filtered_list:
            for s in _radical_sites(m):
                rad_sites.add(s)
            for s in _multipole_bond_sites(m):
                mul_sites.add(s)
        unique_charged = []
        for m in charged_list:
            unique_charged.extend(_find_unique_sites_in_charged_list(
                m, frozenset(rad_sites), frozenset(mul_sites)))

        filtered_list = stabilize_charges_by_electronegativity(filtered_list)
        filtered_list = stabilize_charges_by_proximity(filtered_list)
        if unique_charged:
            unique_charged = stabilize_charges_by_electronegativity(
                unique_charged, allow_empty_list=True)
            unique_charged = stabilize_charges_by_proximity(unique_charged)
            filtered_list.extend(unique_charged)

    if min_span:
        filtered_list = stabilize_charges_by_electronegativity(filtered_list)
        filtered_list = stabilize_charges_by_proximity(filtered_list)

    return filtered_list


def filter_structures(mol_list, original):
    """
    Filter a generated resonance list down to representative structures,
    guaranteeing `original` is present. Returns a list of Molecule.
    """
    if not mol_list:
        return [original]
    mol_list = list(mol_list)
    if original not in mol_list:
        mol_list = [original] + mol_list

    oct_list = get_octet_deviation_list(mol_list)
    filtered, span_list = octet_filtration(mol_list, oct_list)
    if not filtered:
        filtered, span_list = mol_list, get_charge_span_list(mol_list)
    filtered = charge_filtration(filtered, span_list)
    if not filtered:
        filtered = [original]

    # Aromatic-representative preservation (RMG's `aromaticity_filtration`,
    # which runs only for species with `features['is_aromatic']`). The octet
    # pass above would DROP the delocalized aromatic form: `_bond_order` maps
    # a 1.5 aromatic bond to 1 for valence purposes, so a benzene-ring carbon
    # looks like valence 5 (octet deviation 3 per atom). RMG compensates with
    # a dedicated aromaticity pass that re-admits the aromatic representative;
    # here we capture the aromatic form(s) from the input set before filtration
    # and re-attach them if the octet/charge passes dropped them. This is what
    # keeps the 5-form 1-phenylethyl set (the aromatic form is form [0] in
    # RMG-Py) and the benzene aromatic+kek pair (job-01 reference).
    from rmgpu.molecule.resonance import _form_is_aromatic
    aromatic_forms = []
    if _form_is_aromatic(original):
        aromatic_forms.append(original)
    else:
        for m in mol_list:
            if _form_is_aromatic(m):
                aromatic_forms.append(m)

    # Deduplicate by the STRUCTURAL key (positional, bond-order-sensitive,
    # mirroring RMG's `is_identical` under keep_isomorphic=True), NOT the
    # canonical SMILES: the two ortho benzylic forms share a canonical SMILES
    # (different radical position) and the aromatic representative + its
    # kekulized variant also share a canonical SMILES (different ring bond
    # orders) - all must be kept (RMG-Py carries the full 5-form 1-phenylethyl
    # set). Keeping first occurrence preserves the input-first ordering.
    seen = set()
    result = []
    for m in filtered:
        key = _structural_key(m)
        if key not in seen:
            seen.add(key)
            result.append(m)
    # Re-attach any aromatic representative the passes dropped.
    for m in aromatic_forms:
        if _structural_key(m) not in seen:
            seen.add(_structural_key(m))
            result.append(m)
    # Ensure the original structure is present (RMG keeps it first).
    if _structural_key(original) not in seen:
        result.insert(0, original)
    return result
