"""Shared load path for the two vendored Chemprop checkpoints (job-04/step-01).

This is the ONLY code between "checkpoint file on disk" and "raw model output".
The estimators built on top of it (thermo_estimator.py, kinetics_estimator.py)
are responsible for the boundary conversions (PLAN.md 3b):

  thermo    raw -> SI:  value = 10^pred   (H298 J/mol, S298 J/mol/K,
              Cp 7-point grid at 300/400/500/600/800/1000/1500 K, J/mol/K)
  kinetics  raw -> SI:  A = 10^pred_A * degeneracy  (per-site A, CGS
              cm^3/(mol*s)); n and Ea (J/mol) as-is.

LOAD-PATH CONSTRAINT (do not break): both checkpoints pickle-reference the
top-level module ``models`` (``models.BoundedOutputTransform`` and
``models.HuberMetric`` in models/models.py). models/ has no __init__.py, so
the models/ DIRECTORY ITSELF must be importable: we insert the repo's models/
dir at sys.path[0] and ``import models`` resolves to models/models.py. That
directory must stay at the repo root under the name ``models`` and must not
be shadowed by anything else named ``models`` in the interpreter.

The inference pattern is the model team's own: models/predict.py
(chemprop.models.utils.load_model; chemprop.data.{Molecule,Reaction}Dataset
with the checkpoint's featurizer; data.build_dataloader;
pl.Trainer(accelerator, devices=1, logger=False, enable_progress_bar=False)
.predict; torch.cat). The reference baseline in
gates/baselines/job04/reference_predictions.json was generated by running
models/predict.py ITSELF, so the round-trip tests are non-circular.
"""
from __future__ import annotations

import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Sequence

import torch
import torch.nn as nn

from chemprop import data as chemprop_data
from chemprop.models.utils import load_model as chemprop_load_model

# Repo root: rmgpu/ml/base.py -> base.py, ml, rmgpu (package dir), repo root.
REPO_ROOT = Path(__file__).resolve().parents[2]
MODELS_DIR = REPO_ROOT / "models"

THERMO_CKPT_PATH = MODELS_DIR / "chemeleon_thermo_662946.ckpt"
KINETICS_CKPT_PATH = MODELS_DIR / "chemprop_kinetics_662946.ckpt"


def _ensure_models_importable() -> None:
    """Put the repo's models/ dir on sys.path so the checkpoint's pickled
    references to the top-level ``models`` module resolve (load-path
    constraint; see module docstring). A top-level ``models`` import is only
    accepted if it actually carries the checkpoint's classes - a bare
    namespace package (e.g. the repo root's models/ dir shadowing via
    sys.path) is purged and re-imported from models/models.py."""
    cached = sys.modules.get("models")
    if cached is not None and hasattr(cached, "BoundedOutputTransform"):
        return
    if cached is not None:
        for name in [k for k in sys.modules if k == "models" or k.startswith("models.")]:
            del sys.modules[name]
    if str(MODELS_DIR) not in sys.path:
        sys.path.insert(0, str(MODELS_DIR))


def get_device() -> torch.device:
    """CUDA if available, else CPU. Single-GPU-task rule: keep batch sizes
    small; never issue heavy GPU work from multiple sessions at once."""
    return torch.device("cuda" if torch.cuda.is_available() else "cpu")


def _load_featurizers():
    """Import the featurizer instances + target names the checkpoints were
    trained with. The module-level featurizers live in models/models.py
    (top-level ``models``); target names in models/config.py. Both are the
    model team's files, read as-is."""
    _ensure_models_importable()
    from models import CHEMELEON_MOL_FEATURIZER, RIGR_RXN_FEATURIZER  # noqa: F401
    from config import KINETICS_TARGETS, THERMO_TARGETS  # noqa: F401
    return CHEMELEON_MOL_FEATURIZER, RIGR_RXN_FEATURIZER, THERMO_TARGETS, KINETICS_TARGETS


@dataclass(frozen=True)
class ChempropCheckpoint:
    """A loaded vendored checkpoint: model + featurizer + target contract.

    ``targets`` is the ordered tuple of model-native target names
    (models/config.py); ``predict_raw`` returns one row per input in the
    order of ``targets``. Values are RAW (model-native space): for the thermo
    checkpoint all 9 targets are log10 of the physical quantity; for kinetics
    log10_A is log10 of the per-site A, n and Ea are linear. Boundary
    conversion to SI is the estimators' job, not this layer's.
    """

    model: nn.Module
    featurizer: object
    targets: tuple[str, ...]
    checkpoint_path: Path

    def predict_raw(self, datapoints: Sequence, batch_size: int = 8) -> torch.Tensor:
        """Predict on chemprop datapoints (MoleculeDatapoint or
        ReactionDatapoint, matching ``featurizer``); returns a (n, n_targets)
        float32 tensor on CPU, one row per input, in input order.

        Device: pl.Trainer(accelerator=...) picks cuda/cpu exactly like
        models/predict.py; single GPU per machine, so batch_size stays small.
        """
        if isinstance(datapoints[0], chemprop_data.MoleculeDatapoint):
            dset = chemprop_data.MoleculeDataset(list(datapoints), self.featurizer)
        elif isinstance(datapoints[0], chemprop_data.ReactionDatapoint):
            dset = chemprop_data.ReactionDataset(list(datapoints), self.featurizer)
        else:
            raise TypeError(
                f"unsupported datapoint type: {type(datapoints[0]).__name__}"
            )
        loader = chemprop_data.build_dataloader(
            dset, batch_size=batch_size, shuffle=False, drop_last=False
        )
        # drop_last=False is EXPLICIT (deviation from models/predict.py, which
        # leaves it auto): chemprop's default drops the last batch when
        # len(dataset) % batch_size == 1 - at inference that would SILENTLY
        # lose a row. predict_raw must never lose data points.

        import lightning.pytorch as pl
        import predict as _predict  # models/predict.py (holds suppress_lightning_logs)

        with _predict.suppress_lightning_logs():
            trainer = pl.Trainer(
                accelerator="auto",
                devices=1,
                logger=False,
                enable_progress_bar=False,
            )
            raw_preds = trainer.predict(self.model, loader)
        return torch.cat(raw_preds).detach().cpu()


def load_chemprop_model(checkpoint_path: Path | str) -> ChempropCheckpoint:
    """Load ONE vendored checkpoint via the model team's pattern
    (chemprop.models.utils.load_model; models/predict.py). The checkpoint
    decides the featurizer contract, so we select the featurizer/targets by
    the file's identity among the two vendored checkpoints.

    Unknown checkpoint file -> ValueError (no guessing: the checkpoint
    interface is the only model-improvement seam, PLAN.md 8a.3).
    """
    path = Path(checkpoint_path)
    _ensure_models_importable()
    mol_featurizer, rxn_featurizer, thermo_targets, kinetics_targets = (
        _load_featurizers()
    )

    resolved = path.resolve()
    if resolved == THERMO_CKPT_PATH.resolve():
        featurizer, targets = mol_featurizer, tuple(thermo_targets)
    elif resolved == KINETICS_CKPT_PATH.resolve():
        featurizer, targets = rxn_featurizer, tuple(kinetics_targets)
    else:
        raise ValueError(
            f"unknown checkpoint {path!s}; only the two vendored checkpoints "
            f"are known to this load path: {THERMO_CKPT_PATH.name}, "
            f"{KINETICS_CKPT_PATH.name}"
        )

    model = chemprop_load_model(str(path))
    model.eval()
    return ChempropCheckpoint(
        model=model,
        featurizer=featurizer,
        targets=targets,
        checkpoint_path=path,
    )


def load_thermo_checkpoint(path: Path | str = THERMO_CKPT_PATH) -> ChempropCheckpoint:
    """Load models/chemeleon_thermo_662946.ckpt (9 log10-space targets)."""
    return load_chemprop_model(path)


def load_kinetics_checkpoint(path: Path | str = KINETICS_CKPT_PATH) -> ChempropCheckpoint:
    """Load models/chemprop_kinetics_662946.ckpt (log10_A, n, Ea_J_mol)."""
    return load_chemprop_model(path)
